using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Keyboard_Shortcut_API.Models
{
    public static class ModelBuilderExtension
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<OperatingSystem>().HasData(
                new OperatingSystem { Id = 1, Name = "Windows" },
                new OperatingSystem { Id = 2, Name = "MacOS" });

            modelBuilder.Entity<Shortcut>().HasData(
                new Shortcut { Id = 1, Keys = "Ctrl + X", Function = "Cut the selected item.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 2, Keys = "Ctrl + C (or Ctrl + Insert)", Function = "Copy the selected item.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 3, Keys = "Ctrl + V", Function = "Paste the selected item.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 4, Keys = "Ctrl + Z", Function = "Undo an action.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 5, Keys = "Alt + Tab", Function = "Switch between open apps.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 6, Keys = "Alt + F4", Function = "Close/exit the active item/app.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 7, Keys = "Win + L", Function = "Lock your PC.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 8, Keys = "Win + D", Function = "Display and Hide Desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 9, Keys = "F2", Function = "Rename the selected item.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 10, Keys = "F3", Function = "Search for a file or folder in File explorer.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 11, Keys = "F4", Function = "Display the address bar list in File explorer.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 12, Keys = "F5", Function = "Refresh the active window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 13, Keys = "F6", Function = "Cycle through screen elements in a window or on the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 14, Keys = "F10", Function = "Activate the menu bar in the active app.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 15, Keys = "Alt + F8", Function = "Show your password in the sign-in screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 16, Keys = "Alt + Esc", Function = "Cycle through the item in the order in which they were opened.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 17, Keys = "Alt + Underlined letter", Function = "Perform the command for that letter.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 18, Keys = "Alt + Enter", Function = "Display properties for the selected item", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 19, Keys = "Alt + Spacebar", Function = "Open the shortcut menu for the active window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 20, Keys = "Alt + Left arrow", Function = "Go Back", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 21, Keys = "Alt + Right arrow", Function = "Go Forward", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 22, Keys = "Alt + Page Up", Function = "Move up one screen", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 23, Keys = "Alt + Page Down", Function = "Move down one screen", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 24, Keys = "Ctrl + F4", Function = "Close the active document.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 25, Keys = "Ctrl + A", Function = "Select all items in a document or window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 26, Keys = "Ctrl + D (or Delete)", Function = "Delete the selected item and move it to the Recycle Bin.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 27, Keys = "Ctrl + R (or F5)", Function = "Refresh the active window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 28, Keys = "Ctrl + Y", Function = "Redo an action.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 29, Keys = "Ctrl + Right arrow", Function = "Move the cursor to the beginning of the next word.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 30, Keys = "Ctrl + Left arrow", Function = "Move the cursor to the beginning of the previous word.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 31, Keys = "Ctrl + Down arrow", Function = "Move the cursor to the beginning of the next paragraph.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 32, Keys = "Ctrl + Up arrow", Function = "Move the cursor to the beginning of the previous paragraph.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 33, Keys = "Ctrl + Alt + Tab", Function = "Use the arrow key to switch between all open apps.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 34, Keys = "Alt + Shift + Arrow Keys", Function = "When a group or tile is in focus on the Start menu, move it in the direction specified.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 35, Keys = "Ctrl + Shift + Arrow Keys", Function = "When a tile is in focus on the Start menu, move it into another tile to create a folder", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 36, Keys = "Ctrl + Arrow Keys", Function = "Resize the size menu when it's open.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 37, Keys = "Ctrl + Arrow Keys (to move to an item) + Spacebar", Function = "Select multiple individual items in a window or on the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 38, Keys = "Ctrl + Shift with an arrow key", Function = "Select a block of text.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 39, Keys = "Ctrl + Esc", Function = "Open Start.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 40, Keys = "Ctrl + Shift + Esc", Function = "Open Task Manager", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 41, Keys = "Ctrl + Shift", Function = "Switch the keyboard layout when multiple keyboard layouts are available.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 42, Keys = "Ctrl + Spacebar", Function = "turn the Chinese input method editor (IME) on or off.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 43, Keys = "Shift + F10", Function = "Display the shortcut menu for the selected item.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 44, Keys = "Shift with any arrow key", Function = "Select more than one item in a window or on the desktop, or select text in a document.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 45, Keys = "Shift + Delete", Function = "Delete the selected item without moving it to the Recycle Bin first.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 46, Keys = "Right arrow", Function = "Open the next menu to the right, or open a submenu.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 47, Keys = "Left arrow", Function = "Open the next menu to the left, or close a submenu.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 48, Keys = "Esc", Function = "Stop or leave the current task.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 49, Keys = "PrtScn", Function = "Take a screenshot of your whole screen and copy it to the clipboard.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 50, Keys = "Win", Function = "Open or close Start", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 51, Keys = "Win + A", Function = "Open Action center", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 52, Keys = "Win + B", Function = "Set focus in the notification area.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 53, Keys = "Win + C", Function = "Open Cortana in listening mode.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 54, Keys = "Win + Shift + C", Function = "Open the charms menu.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 55, Keys = "Win + D", Function = "Display and hide the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 56, Keys = "Win + Alt + D", Function = "Display and hide the date and time on the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 57, Keys = "Win + E", Function = "Open File Explorer.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 58, Keys = "Win + F", Function = "Open Feedback Hub and take a screenshot.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 59, Keys = "Win + G", Function = "Open Game bar when a game is open.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 60, Keys = "Win + H", Function = "Start dictation.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 61, Keys = "Win + I", Function = "Open Settings.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 62, Keys = "Win + J", Function = "Set focus to a Windows tip when one is available.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 63, Keys = "Win + K", Function = "Open the Connect quick action.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 64, Keys = "Win + L", Function = "Lock your PC or switch accounts.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 65, Keys = "Win + M", Function = "Minimize all windows.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 66, Keys = "Win + O", Function = "Lock device orientation.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 67, Keys = "Win + P", Function = "Choose a presentation display mode.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 68, Keys = "Win + Ctrl + Q", Function = "Open Quick Assist.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 69, Keys = "Win + R", Function = "Open the Run dialog box.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 70, Keys = "Win + S", Function = "Open search.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 71, Keys = "Win + Shift + S", Function = "Take a screenshot of part of your screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 72, Keys = "Win + T", Function = "Cycle through apps on the taskbar.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 73, Keys = "Win + U", Function = "Open Ease of Access Center.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 74, Keys = "Win + V", Function = "Open the clipboard.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 75, Keys = "Win + Shift + V", Function = "Cycle through notifications.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 76, Keys = "Win + X", Function = "Open the Quick Link menu.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 77, Keys = "Win + Y", Function = "Switch input between Windows Mixed Reality and your desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 78, Keys = "Win + Z", Function = "Show the commands available in an app in full-screen mode.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 79, Keys = "Win + period (.) or semicolon (;)", Function = "Open emoji panel.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 80, Keys = "Win + Comma(,)", Function = "Temporarily peek at the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 81, Keys = "Win + Pause", Function = "Display the System Properties dialog box.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 82, Keys = "Win + Ctrl + F", Function = "Search for PCs (if you're on a network).", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 83, Keys = "Win + Shift + M", Function = "Restore minimized windows on the desktop.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 84, Keys = "Win + number", Function = "Open the deskto and start the app pinned to the taskbar in the position indicated by the number. If the app is already running, switch to that app.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 85, Keys = "Win + Shift + number", Function = "Open the desktop and start a new instance of the app pinned to the taskbar in the position indicated by the number.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 86, Keys = "Win + Ctrl + number", Function = "Open the desktop and switch to the last active window of the app pinned to the taskbar in the position indicated by the number.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 87, Keys = "Win + Alt + number", Function = "Open the desktop and open the Jump List for the app pinned to the taskbar in the position indicated by the number.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 88, Keys = "Win + Ctrl + Shift + number", Function = "Open the desktop and open a new instance of the app located at the given position on the taskbar as an administrator.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 89, Keys = "Win + Tab", Function = "Open Task view.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 90, Keys = "Win + Up arrow", Function = "Maximize the window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 91, Keys = "Win + Down arrow", Function = "Remove current app from screen or minimize the desktop window.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 92, Keys = "Win + Left arrow", Function = "Maximize the app or desktop window to the left side of the screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 93, Keys = "Win + Right arrow", Function = "Maximize the app or desktop window to the right side of the screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 94, Keys = "Win + Home", Function = "Minimize all except the active desktop window (restores all windows on second stroke).", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 95, Keys = "Win + Shift + Up arrow", Function = "Strech the desktop window to the top and bottom of the screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 96, Keys = "Win + Shift + Down arrow", Function = "Restore/minimize active desktop windows vertically, maintaining width.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 97, Keys = "Win + Shift + Left or Right arrow", Function = "Move an app or window in the desktop from one monitor to another.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 98, Keys = "Win + Spacebar", Function = "Switch input language and keyboard layout.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 99, Keys = "Win + Ctrl + Spacebar", Function = "Change to a previously selected input.", OsId = 1, Source = "Microsoft" }, 
                new Shortcut { Id = 100, Keys = "Win + Ctrl + Enter", Function = "Turn on Narrator.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 101, Keys = "Win + Plus (+)", Function = "Open Magnifier.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 102, Keys = "Win + forward slash (/)", Function = "Begin IME reconversion.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 103, Keys = "Win + Ctrl + V", Function = "Open shoulder taps.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 104, Keys = "Win + Ctrl + Shift + B", Function = "Wake PC from blank or black screen.", OsId = 1, Source = "Microsoft" },
                new Shortcut { Id = 105, Keys = "Command + X", Function = "Cut the selected item and copy it to the Clipboard.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 106, Keys = "Command + C", Function = "Copy the selected item to the Clipboard. This also works for files in the Finder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 107, Keys = "Command + V", Function = "Paste the contents of the Clipboard into the current document or app. This also works for files in the Finder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 108, Keys = "Command + Z", Function = "Undo the previous command.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 109, Keys = "Shift + Command + Z", Function = "Redo the previous command.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 110, Keys = "Command + A", Function = "Select all items.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 111, Keys = "Command + F", Function = "Find items in a document or open a Find window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 112, Keys = "Command + G", Function = "Find again: Find the next occurrence of the item previously found.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 113, Keys = "Shift + Command + G", Function = "Find the previous occurrence of the item.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 114, Keys = "Command + H", Function = "Hide the windows of the front app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 115, Keys = "Option + Command + H", Function = "View the front app but hide all other apps.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 116, Keys = "Command + M", Function = "Minimize the front window to the Dock.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 117, Keys = "Option + Command + M", Function = "Minimize all windows of the front app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 118, Keys = "Command + O", Function = "Open the selected item, or open a dialog to select a file to open.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 119, Keys = "Command + P", Function = "Print the current document.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 120, Keys = "Command + S", Function = "Save the current document.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 121, Keys = "Command + T", Function = "Open a new tab.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 122, Keys = "Command + W", Function = "Close the front window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 123, Keys = "Option + Command + W", Function = "Close all windows of the app", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 124, Keys = "Option + Command + Esc", Function = "Force quit an app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 125, Keys = "Command + Space bar", Function = "Show or hide the Spotlight search field.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 126, Keys = "Command + Option + Space bar", Function = "Perform a Spotlight search from a finder window", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 127, Keys = "Control + Command + Space bar", Function = "Show the Character Viewer, from which you can choose emoji and other symbols.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 128, Keys = "Control + Command + F", Function = "Use the app in the full screen, if supported by the app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 129, Keys = "Command + Tab", Function = "Switch to the next most recently used app among your open apps.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 130, Keys = "Shift + Command + 5", Function = "Take a screenshot or make a screen recording.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 131, Keys = "Shift + Command + 4", Function = "Take a screenshot.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 132, Keys = "Shift + Command + N", Function = "Create a new folder in the finder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 133, Keys = "Command + Comma (,)", Function = "Open preferences for the front app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 134, Keys = "Option + Command + Power button/Media Eject", Function = "Put your Mac to sleep.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 135, Keys = "Control + Shift + Power button/Media Eject", Function = "Put your displays to sleep.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 136, Keys = "Control + Power button/Media Eject", Function = "Display a dialog asking whether you want to restart, sleep or shut down.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 137, Keys = "Control + Command + Power button", Function = "Force your Mac to restart, without prompting to save any open and unsaved documents.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 138, Keys = "Control + Command + Media Eject", Function = "Quit all apps, then restart your Mac with prompting to save any open and unsaved documents.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 139, Keys = "Control + Option + Command + Power button/Media Eject", Function = "Quit all apps, then shut down your Mac with prompting to save any open and unsaved documents.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 140, Keys = "Control + Command + Q", Function = "Immediately lock your screen.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 141, Keys = "Shift + Command + Q", Function = "Log out of your macOS user account. You will be asked to confirm.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 142, Keys = "Option + Shift + Command + Q", Function = "Log out immediately without confirming.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 143, Keys = "Command + D", Function = "Duplicate the selected files.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 144, Keys = "Command + E", Function = "Eject the selected disk or volume.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 145, Keys = "Command + F", Function = "Start a Spotlight search in the Finder window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 146, Keys = "Command + I", Function = "Show the Get Info window for a selected file.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 147, Keys = "Command + R", Function = "Show the original file for the selected alias, when an alias is selected in the finder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 148, Keys = "Shift + Command + C", Function = "Open the Computer window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 149, Keys = "Shift + Command + D", Function = "Open the desktop folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 150, Keys = "Shift + Command + F", Function = "Open the Recents window, showing all of the files you viewed or changed recently.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 151, Keys = "Shift + Command + G", Function = "Open a Go to Folder window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 152, Keys = "Shift + Command + H", Function = "Open the Home folder of the current macOS user account.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 153, Keys = "Shift + Command + I", Function = "Open iCloud Drive.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 154, Keys = "Shift + Command + K", Function = "Open the Network window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 155, Keys = "Option + Command + L", Function = "Open the Downloads folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 156, Keys = "Shift + Command + N", Function = "Create a new folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 157, Keys = "Shift + Command + O", Function = "Open the Documents folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 158, Keys = "Shift + Command + P", Function = "Show or hide the Preview pane in Finder windows.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 159, Keys = "Shift + Command + R", Function = "Open the AirDrop window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 160, Keys = "Shift + Command + T", Function = "Show or hide the tab bar in Finder windows.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 161, Keys = "Control + Shift + Command + T", Function = "Add selected Finder items to the Dock.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 162, Keys = "Shift + Command + U", Function = "Open the Utilities folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 163, Keys = "Option + Command + D", Function = "Show or hide the Dock.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 164, Keys = "Option + Command + P", Function = "Hide or show the path bar in Finder windows.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 165, Keys = "Option + Command + S", Function = "Hide or show the Sidebar in Finder windows.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 166, Keys = "Command + Slash(/)", Function = "Hide or show the status bar in Finder windows.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 167, Keys = "Command + J", Function = "Show View Options.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 168, Keys = "Command + K", Function = "Open the Connect to Server window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 169, Keys = "Control + Command + A", Function = "Make an alias of the selected item.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 170, Keys = "Command + N", Function = "Open a new Finder window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 171, Keys = "Option + Command + N", Function = "Create a new Smart Folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 172, Keys = "Command + T", Function = "Show or hide the tab bar when a single tab is open in the current Finder window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 173, Keys = "Option + Command + T", Function = "Show or hide the toolbar when a single tab is open in the current Finder window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 174, Keys = "Option + Command + V", Function = "Move the files in the Clipboard from their original location to the current location.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 175, Keys = "Command + Y", Function = "Use Quick Look to preview the selected files.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 176, Keys = "Option + Command + Y", Function = "View a Quick Look slideshow of the selected files.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 177, Keys = "Command + 1", Function = "View the items in the Finder window as icons.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 178, Keys = "Command + 2", Function = "View the items in a Finder window as a list.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 179, Keys = "Command + 3", Function = "View the items in a Finder window in columns.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 180, Keys = "Command + 4", Function = "View the items in a Finder window in a gallery.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 181, Keys = "Command + Left Bracket ([)", Function = "Go to the previous folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 182, Keys = "Command + Right Bracket (])", Function = "Go to the next folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 183, Keys = "Command + Up Arrow", Function = "Open the folder that contains the current folder.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 184, Keys = "Command + Control + Up Arrow", Function = "Open the folder that contains the current folder in a new window.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 185, Keys = "Command + Down Arrow", Function = "Open the selected item.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 186, Keys = "Command + Delete", Function = "Move the selected item to the trash.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 187, Keys = "Shift + Command + Delete", Function = "Empty the trash.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 188, Keys = "Option + Shift + Command + Delete", Function = "Empty the trash without confirmation dialog.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 189, Keys = "Command + Brightness Down", Function = "Turn video mirroring on or off when your Mac is connected to more than one display.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 190, Keys = "Option + Brightness Up/Down", Function = "Open Displays Preferences.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 191, Keys = "Control + Brightness Up/Down", Function = "Change the brightness of your external display.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 192, Keys = "Option + Shift + Brightness Up/Down", Function = "Adjust the display brightness in smaller steps.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 193, Keys = "Option + Mission Control", Function = "Open Mission Control preferences.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 194, Keys = "Command + Mission Control", Function = "Show the desktop.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 195, Keys = "Control + Down arrow", Function = "Show all windows of the front app.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 196, Keys = "Option + Volume Up/Down", Function = "Open Sound preferences.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 197, Keys = "Option + Shift + Volume Up/Down", Function = "Adjust the sound volume in smaller steps.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 198, Keys = "Option + Keyboard Brightness Up/Down", Function = "Open Keyboard preferences.", OsId = 2, Source = "Apple" },
                new Shortcut { Id = 199, Keys = "Option + Shift + Keyboard Brightness Up/Down", Function = "Adjust the keyboard brightness in smaller steps.", OsId = 2, Source = "Apple" }
                );
        }
    }
}
